### ISSUE TITLE
Not Vue 3 compatible

### ISSUE THREAD

**Issue by intositeme** [oleksiikhr/vue-stripe-menu#196]
Can't seem to get it to work with Vue 3.

**Comment by Alexeykhr** [comment]
Hi, I haven't tested it on Vue 3 yet. I'll try later

**Comment by amirhossein95b** [comment]
Hi. I need to use this plugin in vue 3. When will it be updated?

**Comment by amirhossein95b** [comment]
How do I install the new version of npm?

**Comment by Alexeykhr** [comment]
Sorry, very little time, Vue 3 is not supported yet.

**Comment by amirhossein95b** [comment]
Present at least as an alpha version. This way I can not use npm to get dependencies either!

**Comment by amirhossein95b** [comment]
How do I build a library (project | plugin)? When I build, it gives the error that raw-loader and sass-loader are needed. I have installed these two. But it still gives an error. What should I do?

**Comment by dtomlinson91** [comment]
While we wait for the community to port to Vue 3, would you be open to a PR that allows the option of installing under Vue 3? Since the options API isn't deprecated (and you can mix and match both APIs), Vue 3 projects should be able to use this, and using [Vue Demi](https://github.com/vueuse/vue-demi) should allow a seamless installation for an alpha build that still uses the Options API while everything is ported over?
